CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_BLINK_SLEEP_MS=200
CONFIG_LOG=y

# Networking / Wi-Fi
CONFIG_NETWORKING=y
CONFIG_NET_MGMT=y
CONFIG_NET_MGMT_EVENT=y
CONFIG_NET_IPV4=y
CONFIG_NET_IPV6=n
CONFIG_NET_TCP=y
CONFIG_NET_UDP=y
CONFIG_NET_SOCKETS=y
CONFIG_DNS_RESOLVER=y
CONFIG_TEST_RANDOM_GENERATOR=y
# Set these in a local overlay for your network.
CONFIG_WIFI_SSID="Abhaile"
CONFIG_WIFI_PSK="Moran1977"
CONFIG_MQTT_BROKER_HOST="192.168.1.124"
# Networking
CONFIG_MQTT_LIB=y
# WiFi / L2 (already needed for your SSID/PSK)
CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_DHCPV4=y

# Threads
CONFIG_MAIN_STACK_SIZE=4096